name:                skyrim-alchemy
version:             0.1.0.0
author:              "Timofey Peshin"

dependencies:
- base == 4.12.0.0
- containers >= 0.6.0.1
- transformers >= 0.5.6.2
- split >= 0.2.3.3
- lens >= 4.19.2
- fused-effects >= 1.1.0.0
- fused-effects-th >= 0.1.0.2
- bytestring >= 0.10.8.2
- text >= 1.2.3.1
- megaparsec

library:
  source-dirs: src

executables:
  skyrim-alchemy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - skyrim-alchemy
